

# website settings
website:
  title: "Viktor Gradoux"                               
  description: "Viktor is a R and time-series enthusiast !"   
  image: img/logo.png
  
  favicon: img/logo.png
  
  # start of the navigation bar at the top of the website
  navbar:
    pinned: true
    logo: /img/logo.png
    
    # sub-pages
    left:
      - text: "Projects"
        href: projects/index.qmd
      - text: "Code"
        href: Code/index.qmd
      - text: "CV"
        href: cv/index.qmd
    
    # social media 
    right:
      - icon: linkedin
        href: https://ch.linkedin.com/in/viktor-gradoux-b36a55170
      - icon: envelope
        aria-label: email
        href: "mailto:viktor.gradoux@hotmail.com"  
  
  

  search: 
    location: navbar
    type: textbox
  page-footer: 
    left: |
      <span class="faux-block">&#169; 2024 Viktor Gradoux</span>
      
project:
  type: website
  output-dir: docs

  preview: 
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: true

format:
  html:
    fontsize: 1.1em
    theme: 
      - pulse
      - html/styles.scss
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true